// address-book-with-rails/client-ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'address-book';
}
fetch('/api/oddballs').then(resp => resp.json()).then(data => {
  console.log(data);
});


<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
<input type="text" name="search">
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>


  </div>

// address-book-with-rails/client-react/src/App.js
import React, { Component, Fragment } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  componentDidMount() {
    fetch('api/oddballs').then(resp => resp.json()).then(data => {
      console.log(data)
    })
  }
  render() {
    return (
      <div className="App">
          <input
            type="text"
            name="search"
          />
          <ContactList />
      </div>
    );
  }
}

class ContactList extends Component {
  render(){
    return [
      <Contact />,
      <Contact />,
      <Contact />,
      <Contact />
    ]
  }

}

class Contact extends Component {
  render() {
    return(
      <p>Contact</p>
    )
  }
}



export default App;
