// address-book-with-rails/client-ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'address-book';
}
fetch('/api/oddballs').then(resp => resp.json()).then(data => {
  console.log(data);
});


<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
<input type="text" name="search">
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>
  <p>Contact</p>


  </div>

// address-book/client-react/src/App.jsx
import React from "react";
import logo from "./logo.svg";
import "./App.css";

const App = () => {
  React.useEffect(() => {
    fetch("/api/oddballs")
      .then((resp) => {
        return resp.json();
      })
      .then((data) => {
        console.log(data);
      })
      .catch((err) => console.log(err));
  }, []);

  return (
    <div className="App">
      <input type="text" name="search" />
      <ContactList />
    </div>
  );
};

const ContactList = () => {
  return (
    <>
      <Contact />
      <Contact />
      <Contact />
      <Contact />
    </>
  );
};

const Contact = () => {
  return <p>Contact</p>;
};

export default App;
